name: Hello example

on: 
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: First job message
        run: echo "This is the FIRST job!"

  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Second job message
        run: echo "This is the SECOND job, and it runs ONLY after the first."
